# Generated by Django 4.2.11 on 2026-08-07 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdmitCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=350, unique=True)),
                ('organization', models.CharField(max_length=200)),
                ('exam_name', models.CharField(max_length=300)),
                ('exam_date', models.DateField(blank=True, null=True)),
                ('release_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('download_url', models.URLField(blank=True, help_text='Direct link to download admit card', max_length=500)),
                ('official_website_url', models.URLField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('views', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-release_date'],
            },
        ),
    ]
