# Generated by Django 4.2.11 on 2026-08-07 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Bootstrap icon class or icon name', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=350, unique=True)),
                ('organization', models.CharField(max_length=200)),
                ('short_description', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('total_vacancies', models.PositiveIntegerField(default=0)),
                ('qualification', models.CharField(blank=True, max_length=200)),
                ('age_min', models.PositiveIntegerField(blank=True, null=True)),
                ('age_max', models.PositiveIntegerField(blank=True, null=True)),
                ('age_relaxation', models.CharField(blank=True, max_length=200)),
                ('salary', models.CharField(blank=True, max_length=200)),
                ('job_location', models.CharField(blank=True, max_length=200)),
                ('application_start_date', models.DateField(blank=True, null=True)),
                ('application_last_date', models.DateField(blank=True, null=True)),
                ('exam_date', models.DateField(blank=True, null=True)),
                ('admit_card_date', models.DateField(blank=True, null=True)),
                ('application_fee_general', models.CharField(blank=True, max_length=50)),
                ('application_fee_obc', models.CharField(blank=True, max_length=50)),
                ('application_fee_sc', models.CharField(blank=True, max_length=50)),
                ('application_fee_st', models.CharField(blank=True, max_length=50)),
                ('application_fee_female', models.CharField(blank=True, max_length=50)),
                ('selection_process', models.TextField(blank=True)),
                ('eligibility', models.TextField(blank=True)),
                ('how_to_apply', models.TextField(blank=True)),
                ('important_instructions', models.TextField(blank=True)),
                ('official_notification_url', models.URLField(blank=True, max_length=500)),
                ('official_apply_url', models.URLField(blank=True, max_length=500)),
                ('official_website_url', models.URLField(blank=True, max_length=500)),
                ('featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('apply_now', 'Apply Now'), ('closing_soon', 'Closing Soon'), ('closed', 'Application Closed'), ('exam_soon', 'Exam Soon'), ('result_declared', 'Result Declared')], default='upcoming', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='jobs.category')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='jobs.state')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='jobs.job')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order'],
            },
        ),
    ]
