# Generated by Django 4.2.11 on 2026-08-07 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=350, unique=True)),
                ('organization', models.CharField(max_length=200)),
                ('exam_name', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('exam_pattern', models.TextField(blank=True, help_text='Detailed exam pattern')),
                ('syllabus_content', models.TextField(blank=True, help_text='Full syllabus content')),
                ('official_notification_url', models.URLField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Syllabi',
                'ordering': ['-created_at'],
            },
        ),
    ]
